# Generated by Django 4.0.1 on 2022-01-28 14:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.IntegerField(choices=[(2, 'VIPClient'), (3, 'CLIENT'), (1, 'ADMIN')], default=3, verbose_name='Тип Пользователя')),
                ('phone_number', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'MALE'), (3, 'OTHER'), (2, 'FEMALE')], verbose_name='Гендер')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
