# Generated by Django 4.0.1 on 2022-02-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.IntegerField(choices=[(2, 'FEMALE'), (1, 'MALE'), (3, 'OTHER')], verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'VIPClient'), (3, 'CLIENT')], default=3, verbose_name='Тип Пользователя'),
        ),
    ]
